# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Analysis configuration
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include GUI files
        ('gui', 'gui'),
        # Include scripts directory and subdirectories
        ('scripts', 'scripts'),
        ('scripts/core', 'scripts/core'),
        ('scripts/utils', 'scripts/utils'),
        ('scripts/visualization', 'scripts/visualization'),
        ('scripts/config', 'scripts/config'),
        # Include main utils directory
        ('utils', 'utils'),
        # Include data files
        ('data', 'data'),
        # Include analysis results
        ('analysis', 'analysis'),
        # Include elevation cache
        ('elevation_cache', 'elevation_cache'),
        # Include documentation
        ('README.md', '.'),
        ('README_GUI.md', '.'),
        ('README_GUI_DE.md', '.'),
        # Include requirements
        ('requirements.txt', '.'),
        # Include desktop file
        ('GPS_Analysis_Suite.desktop', '.'),
    ],
    hiddenimports=[
        # GUI modules
        'gui.analysis_mode_selector',
        'gui.live_map_2d_gui',
        'gui.visualization_3d_gui',
        # Script modules
        'scripts',
        'scripts.gps_utils',
        'scripts.animate_live_map',
        'scripts.animation_3d',
        'scripts.mobile_animation',
        'scripts.proximity_analysis_gui',
        'scripts.proximity_analysis',
        'scripts.i18n',
        'scripts.update_manager',
        # Add direct gps_utils import
        'gps_utils',
        # Core modules
        'core',
        'core.animation_3d_engine',
        'core.elevation_data_manager',
        'core.mobile_animation_engine',
        'core.proximity_engine',
        'core.trail_system',
        # Utils modules
        'utils',
        'utils.user_interface_3d',
        'utils.user_interface',
        'utils.mobile_interface',
        'utils.performance_optimizer',
        # Visualization modules
        'visualization',
        'visualization.proximity_plots',
        # Standard library modules that might be needed
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.backends.backend_tkagg',
        'folium',
        'branca',
        'pandas',
        'numpy',
        'scipy',
        'scipy.spatial',
        'geopy',
        'geopy.distance',
        'requests',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'json',
        'csv',
        'datetime',
        'time',
        'os',
        'sys',
        'pathlib',
        'functools',
        'collections',
        'itertools',
        'math',
        'random',
        'logging',
        'threading',
        'multiprocessing',
        'subprocess',
        'webbrowser',
        'urllib',
        'urllib.request',
        'urllib.parse',
        'http',
        'http.client',
        'ssl',
        'socket',
        'platform',
        'shutil',
        'tempfile',
        'zipfile',
        'gzip',
        'bz2',
        'lzma',
        'hashlib',
        'hmac',
        'secrets',
        'uuid',
        'calendar',
        'locale',
        'gettext',
        'argparse',
        'optparse',
        'getopt',
        'configparser',
        'sqlite3',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'html',
        'html.parser',
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'smtplib',
        'imaplib',
        'poplib',
        'ftplib',
        'telnetlib',
        'xmlrpc',
        'xmlrpc.client',
        'xmlrpc.server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GPS_Analysis_Suite',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
